version: "3.8"
services:
  app:
    image: my-spring-app:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs

  loki:
    image: grafana/loki:2.8.2
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml:ro
      - ./loki-data/index:/loki/index
      - ./loki-data/chunks:/loki/chunks
      - ./loki-data/wal:/wal
      - ./loki-data/cache:/loki/cache
      - ./loki-data/compactor:/loki/compactor

  promtail:
    image: grafana/promtail:2.8.2
    command:
      - -config.file=/etc/promtail/promtail-config.yaml
    volumes:
      - ./promtail-config.yaml:/etc/promtail/promtail-config.yaml:ro
      - ./logs:/var/log/spring-app:ro

  grafana:
    image: grafana/grafana:9.2.0
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin"
