server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: spring-app
    static_configs:
      - targets: ["localhost"]
        labels:
          app: spring-app
          __path__: /var/log/spring-app/*.log
